

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'

export function Astronaut(props) {
  const group = useRef()

  const { nodes, materials, animations } =
    useGLTF('/models/tenhun_falling_spaceman_fanart.glb')

  const { actions } = useAnimations(animations, group)

  // ✅ FIX 1: stable motion values (useRef)
  const yPosition = useRef(useMotionValue(5)).current
  const ySpring = useSpring(yPosition, {
    damping: 20,
    stiffness: 100,
  })

  // ✅ FIX 2: proper animation start
  useEffect(() => {
    if (!actions || animations.length === 0) return

    const action = actions[animations[0].name]
    action?.reset().fadeIn(0.5).play()

    return () => action?.fadeOut(0.5)
  }, [actions, animations])

  // ✅ FIX 3: trigger fall once
  useEffect(() => {
    yPosition.set(-1)
  }, [yPosition])

  // ✅ FIX 4: safe + smooth frame update
  useFrame(() => {
    if (!group.current) return
    group.current.position.y = ySpring.get()
  })

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale || 0.3}
      position={props.position || [1.3, -1, 0]}
    >
      <primitive object={nodes.metarig_rootJoint} />

      {Object.values(nodes).map((node, i) => {
        if (node.type === "SkinnedMesh") {
          return (
            <skinnedMesh
              key={i}
              geometry={node.geometry}
              material={node.material}
              skeleton={node.skeleton}
            />
          )
        }
        return null
      })}
    </group>
  )
}

useGLTF.preload('/models/tenhun_falling_spaceman_fanart.glb')



